name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 69.48.181.96
          username: bluevult
          password: ${{ secrets.CPANEL_PASSWORD }}
          script: |
            cd /home/bluevult/repositories/bluevult-permanent-lights
            git pull
            rm -rf /home/bluevult/public_html/assets
            rm -f /home/bluevult/public_html/index.html
            rm -f /home/bluevult/public_html/.htaccess
            cp -R dist/. /home/bluevult/public_html/