name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build

      - name: Copy build to server via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 69.48.181.96
          username: bluevult
          password: ${{ secrets.CPANEL_PASSWORD }}
          source: "dist/*"
          target: "/home/bluevult/public_html"
          strip_components: 1